services:
  postgres:
    # image: postgres-aula
    image: postgres:16
    container_name: postgres-aula
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sua_senha
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - ~/Projetos/volumes-docker/postgres-aula/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5