services:
  postgres:
    image: postgres-aula
    # image: postgres:13
    container_name: postgres-missoes
    # env_file: .env  # Carrega as variáveis do arquivo .env
    shm_size: 512mb
    restart: always
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    ports:
      - '8090:5432'
    volumes:
      - ~/Projetos/volumes-docker/postgres-missoes/:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5