services:
  postgres:
    image: postgres-aula
    container_name: postgres-aula-env
    env_file: .env  # Carrega as variáveis do arquivo .env
    shm_size: 512mb
    restart: always
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    ports:
      - '5432:5432'
    volumes:
      - ~/Projetos/volumes-docker/postgres-aula/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5