services:
  postgres:
    image: postgres-aula
    # image: postgres:16
    container_name: postgres-aula-interm
    restart: always
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: meu_usuario
      POSTGRES_PASSWORD: minha_senha
      POSTGRES_DB: meu_banco
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ~/Projetos/volumes-docker/postgres-aula/data3:/var/lib/postgresql/data
      - ~/Projetos/volumes-docker/postgres-aula/data3/init-scripts:/docker-entrypoint-initdb.d
    networks:
      - minha_rede
    command: postgres -c 'config_file=/custom-config/postgresql.conf'
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5

networks:
  minha_rede:
    driver: bridge
