services:
  postgres:
    image: postgres-aula
    # image: postgres:13
    container_name: postgres-aula-interm-propriedades
    restart: always
    shm_size: "512m"                  # Aumenta o tamanho da memória compartilhada
    ulimits:
      nproc: 65535
      nofile:
        soft: 8192
        hard: 16384
    sysctls:
      net.core.somaxconn: 1024
      kernel.shmmax: 268435456
      kernel.shmall: 2097152
    mem_limit: "2g"
    mem_reservation: "1g"
    cpus: "1.5"
    ports:
      - "5432:5432"
    volumes:
      - ~/Projetos/volumes-docker/postgres-aula/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    tmpfs:
      - /tmp
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5
