services:
  postgres:
    image: postgres-aula
    # image: postgres:16
    container_name: postgres-aula-avancado-env
    restart: always
    shm_size: "512m"
    ulimits:
      nproc: 65535
      nofile:
        soft: 8192
        hard: 16384
    sysctls:
      net.core.somaxconn: 1024
      kernel.shmmax: 268435456
      kernel.shmall: 2097152
    mem_limit: "2g"
    mem_reservation: "1g"
    cpus: "1.5"
    ports:
      - "5438:5432"
    volumes:
      - "${PGDATA6}:/var/lib/postgresql/data"  # Mapeamento do volume usando variável do .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    tmpfs:
      - /tmp
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5
